# Generated by Django 3.1.2 on 2020-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(db_index=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
